lab2/django_project/actor/urls.py
from django.urls import path
from .views import actors_list, actor_details, actor_create, actor_update, actor_delete

app_name = 'actor'

urlpatterns = [
    path('list', actors_list, name='list'),
    path('create', actor_create, name='create'),
    path('update/<int:pk>', actor_update, name='update'),
    path('actor/<int:pk>', actor_details, name='detail'),
    path('actor/delete/<int:pk>', actor_delete, name='delete')
]

lab2/django_project/django_project/urls.py
from xml.etree.ElementInclude import include

from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls')),
    path('actor/', include('actor.urls')),
    path('movie/', include('movie.urls')),
    path('billing/', include('billing.urls')),
    path('account/', include('django.contrib.auth.urls'))

]

from django.conf import settings

if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lab2/django_project/todo/urls.py
from django.urls import path

from .views import todo_home, todo_template, todo_list, todo_details, todo_delete, todo_state, todo_add, todo_update

app_name = 'todo'
urlpatterns = [

    path('list', todo_list, name='list'),
    path('tem', todo_template, name='html temp'),
    path('detail/<str:VarToUseInApp>', todo_details, name='todo-detail'),
    path('home/<str:VarToUseInApp>', todo_home, name='todo-home'),
    path('delete/<str:VarToUseInApp>', todo_delete, name='todo-delete'),
    path('state/<str:VarToUseInApp>', todo_state, name='todo-state'),
    path('add', todo_add, name='todo-add'),
    path('update/<str:VarToUseInApp>', todo_update, name='todo-update')
]

# reverse('todo:home') ->/todo/home

lab2/django_project/actor/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Actor(models.Model):
    NATIONALITIES = (
        ('eg', 'Egyptian'),
        ('ksa', 'Saudi Arabian'),
        ('kuwait', 'Kuwait Citizen'),
    )

    GENDER = (
        ('m', 'Male'),
        ('f', 'Female'),
    )

    name = models.fields.CharField(verbose_name=_('Actor Name'), max_length=50)
    gender = models.fields.CharField(choices=GENDER, max_length=1, default='m')
    age = models.fields.PositiveIntegerField()
    nationality = models.fields.CharField(choices=NATIONALITIES, max_length=6)

    def __str__(self):
        return self.name

lab2/django_project/actor/forms.py
from django.forms import ModelForm
from .models import Actor


class ActorForm(ModelForm):
    class Meta:
        model = Actor
        fields = '__all__'

    def as_my_custom_display(self):
        return "<h1>HIii</h1>"

    #  def save()
            #self.model.obejcts.create(name=name)

lab2/django_project/actor/views.py
from django.shortcuts import render, redirect, reverse
from .models import Actor
from .forms import ActorForm


def actors_list(request):
    actors = Actor.objects.all()
    return render(request, template_name='actor/actor_list.html', context={'actors': actors})


def actor_create(request):
    if request.method == 'GET':
        form = ActorForm()
        return render(request, template_name='actor/actor_create.html', context={'form': form})

    elif request.method == 'POST':
        form = ActorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('actor:list'))


def actor_details(request, pk):
    actor = Actor.objects.get(pk=pk)
    return render(request, template_name='actor/actor_details.html', context={'actor_data': actor})


def actor_delete(request, pk):
    actor = Actor.objects.get(pk=pk)
    actor.delete()
    return redirect(reverse('actor:list'))


def actor_update(request, pk):
    actor = Actor.objects.get(pk=pk)
    if request.method == 'GET':
        form = ActorForm(instance=actor)
        return render(request, template_name='actor/actor_update.html', context={'form': form, 'actor': actor})

    elif request.method == 'POST':
        form = ActorForm(request.POST, instance=actor)
        if form.is_valid():
            form.save()
            return redirect(reverse('actor:list'))

lab2/django_project/actor/templates/actor/actor_create.html
{% extends 'base.html' %}
{% block content %}

<h1>Actor create</h1>
<form action="{% url 'actor:create'%}" method="POST">
    {% csrf_token %}

    {{form.as_p}}

    <button type="submit">Create</button>

</form>


{% endblock %}

lab2/django_project/actor/templates/actor/actor_details.html
{% extends 'base.html'%}

{% block content%}

Name: {{actor_data.name}}
Age:{{actor_data.age}}
Nation.:{{actor_data.nationality}}
Gender: {{actor_data.gender}}


{% endblock%}

lab2/django_project/actor/templates/actor/actor_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Actor list</h1>
<a class="btn btn-success" href="{% url 'actor:create'%}"> Create Actor</a>

<table class="table table-condensed">
    <thead>
    <tr>
        <td>Actor Name</td>
        <td>Actor Gender</td>
        <td>Actor Age</td>
        <td>Actor Nationality</td>
        <td>Actions Nationality</td>
    </tr>
    </thead>
    <tbody>{% for actor in actors %}


    <tr>
        <td> {{actor}}</td>
        <td>
            {{actor.gender}}
        </td>
        <td>
            {{actor.age}}
        </td>
        <td>
            {{actor.nationality}}
        </td>

        <td>
            <a href="{% url 'actor:update' actor.id%}"> Update</a>
            <a href="{% url 'actor:delete' actor.id %}">Delete </a>
            <a href="{% url 'actor:detail' actor.id%}"> Details</a>
        </td>
    </tr>

    {% endfor %}


    </tbody>
</table>

{% endblock %}

lab2/django_project/actor/templates/actor/actor_update.html
{% extends 'base.html'%}

{% block content %}
<form method="POST" action="{% url 'actor:update' actor.id %}">
    {% csrf_token%}
    {{form.as_p}}
    <button type="submit">Update Actor</button>
</form>

{% endblock%}