lab4/django_project/django_project/urls.py
from xml.etree.ElementInclude import include

from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),
    path('todo/', include('todo.urls')),
    path('actor/', include('actor.urls')),
    path('movie/', include('movie.urls')),
    path('billing/', include('billing.urls')),
    path('account/', include('django.contrib.auth.urls')),
    path('account/', include('account.urls')),
    path('movie/api/v1/', include('movie.api.v1.urls')),
    path('actor/api/v1/', include('actor.api.v1.urls')),
    path('account/api/v1/', include('account.api.v1.urls'))

]

from django.conf import settings

if settings.DEBUG:
    from django.conf.urls.static import static

    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

lab4/django_project/todo/urls.py
from django.urls import path

from .views import todo_home, todo_template, todo_list, todo_details, todo_delete, todo_state, todo_add, todo_update

app_name = 'todo'
urlpatterns = [

    path('list', todo_list, name='list'),
    path('tem', todo_template, name='html temp'),
    path('detail/<str:VarToUseInApp>', todo_details, name='todo-detail'),
    path('home/<str:VarToUseInApp>', todo_home, name='todo-home'),
    path('delete/<str:VarToUseInApp>', todo_delete, name='todo-delete'),
    path('state/<str:VarToUseInApp>', todo_state, name='todo-state'),
    path('add', todo_add, name='todo-add'),
    path('update/<str:VarToUseInApp>', todo_update, name='todo-update')
]

# reverse('todo:home') ->/todo/home

lab4/django_project/todo/models.py
from django.db import models


class Todo(models.Model):
    name = models.fields.CharField(verbose_name="Todo Name", max_length=100, unique=True)
    priority = models.fields.IntegerField(verbose_name="Todo Priority", default=1)
    todo_date = models.fields.DateField(verbose_name="Date", default='2000-01-01')
    is_done = models.fields.BooleanField(default=False)
    notes = models.fields.TextField(default='')

    creation_time = models.DateTimeField(auto_now_add=True)
    update_time = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"Todo: {self.name} At Time {self.creation_time}"

    class Meta:
        verbose_name = 'Todo'
        verbose_name_plural = 'Todos'
        ordering = ('-creation_time',)


class Task(models.Model):
    name = models.fields.CharField(verbose_name="Task Name", max_length=100)
    todo = models.ForeignKey('todo', on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f"Task {self.id} For Todo : {self.todo.name}"

lab4/django_project/todo/views.py
from django.shortcuts import render, HttpResponse, redirect, reverse
from django.contrib import messages
books = {
    '1': {'Author': 'Youssef', 'pages': 50, 'status': False},
    '2': {'Author': 'Ibrahim', 'pages': 40, 'status': False},
    '3': {'Author': 'Salama', 'pages': 90, 'status': False}
}


def todo_home(request, **kwargs):
    print(kwargs)
    the_url_var = kwargs.get('VarToUseInApp')
    print(the_url_var)
    result = books.get(the_url_var)
    return HttpResponse(f"Hello From Django {result}")


def todo_template(request):
    print('true')
    return render(request, 'todo/template.html')


def todo_list(request):
    return render(request, 'todo/todo.html', context={'collection': books})


def todo_details(request, **kwargs):
    the_url_var = kwargs.get('VarToUseInApp')
    print(the_url_var)
    result = books.get(the_url_var)
    return render(request, 'todo/details.html', context={'element': result})


def todo_delete(request, **kwargs):
    the_url_var = kwargs.get('VarToUseInApp')
    print(the_url_var)
    result = books.get(the_url_var)
    if result.get('status'):
        print('ok')
        books.pop(the_url_var)
        return redirect(reverse('todo:list'))
    else:
        print('else')
        return render(request, 'todo/todo.html',
                      context={'warning_msg': "can not delete flase status", 'collection': books})


def todo_state(request, **kwargs):
    book = kwargs.get('VarToUseInApp')
    print(book)
    result = books.get(book)
    result['status'] = True
    print(result)
    print(books)
    return redirect(reverse('todo:list'))


def todo_update(request, **kwargs):
    print(books)
    book = kwargs.get('VarToUseInApp')
    result = books.get(book)
    print(result)
    return render(request, 'todo/todo_update.html', context={'element': result})


def todo_edit(request):
    author = request.POST['author']
    pages = request.POST['pages']
    state = False
    count = len(books.keys())
    books[f"{count + 1}"] = {'Author': author, 'pages': pages, 'status': state}


def todo_add(request):
    print("ok")
    author = request.POST['author']
    pages = request.POST['pages']
    state = False
    # print(author+pages+state)
    count = len(books.keys())
    books[f"{count + 1}"] = {'Author': author, 'pages': pages, 'status': state}
    message="bfbdfbdfb"
    # return render(request, 'todo/todo.html', context={"msg22": "added successfully", 'collection': books})
    messages.success(request, 'Profile details updated.')
    return redirect('todo:list')

lab4/django_project/todo/templates/todo/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>base</title>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">

</head>
<body>
<h1>base file</h1>
{% block content %}
{% endblock %}
</body>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

</html>

lab4/django_project/todo/templates/todo/details.html
{% extends 'base.html' %}

{% block content %}
<!--<h1>Name : {{element}} </h1>-->

<table class="table table-dark">
  <thead>
    <tr>

      <th scope="col">Author</th>
      <th scope="col">Pages</th>
      <th scope="col">State</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>{{element.Author}}</td>
      <td>{{element.pages}}</td>
      <td>{{element.status}}</td>
    </tr>
  </tbody>
</table>
{% endblock %}

lab4/django_project/todo/templates/todo/template.html
{% extends 'todo/base.html' %}


{% block content%}
<h1>the First Template in Django</h1>
{% endblock %}

lab4/django_project/todo/templates/todo/todo.html
{% extends 'todo/base.html' %}

{% block content%}

<!--{% for todo1,value in collection.items %}-->

<!--{{todo1}} : {{value}}  : <a href="{% url 'todo:todo-detail' todo1%}">Details</a>-->

<!--{% endfor %}-->
<form method="post" action="/todo/add">
     {% csrf_token %}
 <div class="w-25">
    <label  class="visually-hidden">Password</label>
    <input type="text" class="form-control" name="author" placeholder="Author" required><br>
  </div>
  <div class="w-25">
    <label  class="visually-hidden">Password</label>
    <input type="number" class="form-control" name="pages"  placeholder="Pages" required>
  </div>
<br>
  <div class="col-auto">

  <button class="btn btn-success" type="submit"> Add</button>
  </div>
</form>
<br>
{% if warning_msg%}
<div class="alert alert-danger">{{warning_msg}}</div>
{% endif %}

{% if msg22 %}
<div class="alert alert-success">{{msg22}}</div>
{% endif %}

{% if messages %}
    {% for message in messages %}
    <div class="alert alert-success" {% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</div>
    {% endfor %}
{% endif %}

<table class="table">
  <thead class="thead-dark">
    <tr>
      <th scope="col">#</th>
      <th scope="col">Author</th>
      <th scope="col">Pages</th>
      <th scope="col">Status</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
  {% for todoID,value in collection.items %}
    <tr>
      <th scope="row">{{todoID}}</th>
      <td>{{value.Author}}</td>
      <td>{{value.pages}}</td>
      <td>{{value.status}}</td>
      <td> <a class="btn btn-success " href="{% url 'todo:todo-detail' todoID%}">Details</a><a class="btn btn-info mx-2" href="{% url 'todo:todo-state' todoID%}">State</a><a class="btn btn-danger" href="{% url 'todo:todo-delete' todoID%}">Delete</a><a class="btn btn-primary mx-2" href="{% url 'todo:todo-update' todoID%}">Update</a></td>
    </tr>
   {% endfor %}

  </tbody>
</table>


{%endblock%}

lab4/django_project/todo/templates/todo/todo_update.html
{% extends 'todo/base.html' %}

{% block content %}

<form method="post" action="/todo/add">
     {% csrf_token %}
 <div class="w-25">
    <label  class="visually-hidden">Password</label>
    <input type="text" class="form-control" name="author" placeholder="Author" value={{element.Author}} required><br>
  </div>
  <div class="w-25">
    <label  class="visually-hidden">Password</label>
    <input type="number" class="form-control" name="pages" value={{element.pages}}  placeholder="Pages" required>
  </div>
<br>
  <div class="col-auto">

  <button class="btn btn-success" type="submit"> Edit</button>
  </div>
</form>


{%endblock%}